name: Setup
runs:
  using: 'composite'
  steps:
    - name: Install Node.js 18.x
      uses: actions/setup-node@b39b52d1213e96004bfcb1c61a8a6fa8ab84f3e8 # v4
      with:
        node-version: 18.x
        cache: npm
        registry-url: 'https://registry.npmjs.org'

    - name: Install
      env:
        CI: true
      shell: bash
      run: |
        yarn install
